Support schedule
grails/grails-static-website pull request #259
Opened 2022-06-20 15:14 UTC by devaughns

Creates a static page dedicated to the support schedule for the various Grails versions.

2022-06-20 15:14 UTC, devaughns commented on pages/support-schedule.html
> +							the framework.</strong>
Filler wording from the copy

2022-06-20 15:15 UTC, devaughns commented on pages/support-schedule.html
> +					</section>
Additional placeholder headers and wording from the copy

2022-06-24 14:56 UTC, JasonTypesCodes requested changes
I'll fill in the final copy and get this merged.  Thanks!

2022-06-28 15:47 UTC, JasonTypesCodes approved these changes

2022-06-28 15:48 UTC, merged