Restyle columns to single column
grails/grails-static-website pull request #294
Opened 2023-08-21 01:04 UTC by Richardson-e

2023-08-21 06:12 UTC, sdelamo reviewed
With this changes, the design creates a huge blank space 

![IMG_7599](https://github.com/grails/grails-static-website/assets/864788/3b4e7996-9bdc-4d37-a31a-5cb63a2bee63)

2023-08-21 06:12 UTC, sdelamo commented on buildSrc/src/main/groovy/org/grails/plugin/PluginsPage.groovy
> -//                ul(class: 'iconlinks') {
I would delete this commented out code.

2023-08-22 09:22 UTC, sdelamo requested changes
Please, remove commented out code.

2023-08-28 13:04 UTC, puneetbehl requested changes

2023-08-28 13:04 UTC, puneetbehl commented on assets/javascripts/plugins-search.js
> +//    }
Please delete this code.

2023-09-11 14:13 UTC, merged